//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eossyn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterClass
    {
        public CharacterClass()
        {
            this.UserCharacters = new HashSet<UserCharacter>();
        }
    
        public int CharacterClassId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<UserCharacter> UserCharacters { get; set; }
    }
}
