//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eossyn.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EossynEntities : DbContext
    {
        public EossynEntities()
            : base("name=EossynEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<User> Users { get; set; }
        public DbSet<CharacterClass> CharacterClasses { get; set; }
        public DbSet<CharacterFaction> CharacterFactions { get; set; }
        public DbSet<CharacterRace> CharacterRaces { get; set; }
        public DbSet<UserCharacter> UserCharacters { get; set; }
        public DbSet<UserSession> UserSessions { get; set; }
        public DbSet<World> Worlds { get; set; }
    }
}
