//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eossyn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSetting
    {
        public System.Guid UserId { get; set; }
        public System.Guid LastUsedCharacterId { get; set; }
        public System.Guid LastUsedWorldId { get; set; }
    
        public virtual User User { get; set; }
        public virtual UserCharacter UserCharacter { get; set; }
        public virtual World World { get; set; }
    }
}
