//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eossyn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCharacter
    {
        public UserCharacter()
        {
            this.UserSettings = new HashSet<UserSetting>();
        }
    
        public System.Guid UserCharacterId { get; set; }
        public System.Guid UserId { get; set; }
        public string CharacterName { get; set; }
        public int CharacterRaceId { get; set; }
        public System.Guid WorldId { get; set; }
        public int CharacterClassId { get; set; }
        public int CurrentLevel { get; set; }
    
        public virtual CharacterClass CharacterClass { get; set; }
        public virtual CharacterRace CharacterRace { get; set; }
        public virtual User User { get; set; }
        public virtual World World { get; set; }
        public virtual ICollection<UserSetting> UserSettings { get; set; }
    }
}
